metadata = {
    "version": "0.14.0",
    "author": "Tobias Brox",
    "author_short": "tobixen",
    "copyright": "Copyright 2013-2022, Tobias Brox and contributors",
    "license": "GPLv3+",
    "license_url": "http://www.gnu.org/licenses/gpl-3.0-standalone.html",
    "maintainer": "Tobias Brox",
    "author_email": "t-calendar-cli@tobixen.no",
    "status": "Development",
    "product": "calendar_cli",
    "name": "calendar_cli",
    "description": "Simple command-line CalDav client, for adding and browsing calendar items, todo list items, etc.",
    "url": "https://github.com/tobixen/calendar-cli",
}
